using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LeetCodeTests.Tests;

namespace LeetCodeTests
{
    class Program
    {
        static void Main(string[] args)
        {
            //new A0001TwoSum().Test();
            //new A0002AddTwoNumbers().Test();
            //new A0003LengthOfLongestSubstring().Test();
            //new A0004FindMedianSortedArrays().Test();//TODO
            //new A0005LongestPalindrome().Test();
            //new A0006Convert().Test();
            //new A0007Reverse().Test();
            //new A0008MyAtoi().Test();
            //new A0009IsPalindrome().Test();
            //new A0010IsMatch().Test();
            //new A0011MaxArea().Test();
            //new A0012IntToRoman().Test();
            //new A0013RomanToInt().Test();
            //new A0014LongestCommonPrefix().Test();
            //new A0015ThreeSum().Test();
            //new A0016ThreeSumClosest().Test();
            //new A0017LetterCombinations().Test();
            //new A0018FourSum().Test();
            //new A0019RemoveNthFromEnd().Test();
            //new A0020IsValid().Test();
            //new A0021MergeTwoLists().Test();
            //new A0022GenerateParenthesis().Test();
            //new A0023MergeKLists().Test();
            //new A0024SwapPairs().Test();
            //new A0025ReverseKGroup().Test();
            //new A0026RemoveDuplicates().Test();
            //new A0027RemoveElement().Test();
            //new A0028StrStr().Test();
            //new A0029Divide().Test();
            //new A0030FindSubstring().Test();
            //new A0031NextPermutation().Test();
            //new A0032LongestValidParentheses().Test();
            //new A0033Search().Test();
            //new A0034SearchRange().Test();
            //new A0035SearchInsert().Test();
            //new A0036IsValidSudoku().Test();
            //new A0037SolveSudoku().Test();
            //new A0038CountAndSay().Test();
            //new A0039CombinationSum().Test();
            //new A0040CombinationSum2().Test();
            //new A0041FirstMissingPositive().Test();
            //new A0042Trap().Test();
            //new A0043Multiply().Test();
            //new A0044IsMatch().Test();
            //new A0045Jump().Test();
            //new A0046Permute().Test();
            //new A0047PermuteUnique().Test();
            //new A0048Rotate().Test();
            //new A0049GroupAnagrams().Test();
            //new A0050MyPow().Test();
            //new A0051SolveNQueens().Test();
            //new A0052TotalNQueens().Test();
            //new A0053MaxSubArray().Test();
            //new A0054SpiralOrder().Test();
            //new A0055CanJump().Test();
            //new A0056Merge().Test();
            //new A0057Insert().Test();
            //new A0058LengthOfLastWord().Test();
            //new A0059GenerateMatrix().Test();
            //new A0060GetPermutation().Test();
            //new A0061RotateRight().Test();
            //new A0062UniquePaths().Test();
            //new A0063UniquePathsWithObstacles().Test();
            //new A0064MinPathSum().Test();
            //new A0065IsNumber().Test();
            //new A0066PlusOne().Test();
            //new A0067AddBinary().Test();
            //new A0068FullJustify().Test();
            //new A0069MySqrt().Test();
            //new A0070ClimbStairs().Test();
            //new A0071SimplifyPath().Test();
            //new A0072MinDistance().Test();
            //new A0073SetZeroes().Test();
            //new A0074SearchMatrix().Test();
            //new A0075SortColors().Test();
            //new A0076MinWindow().Test();
            //new A0077Combine().Test();
            //new A0078Subsets().Test();
            //new A0079Exist().Test();
            new A0080RemoveDuplicates().Test();
        }
    }
}
